### ISSUE TITLE
Hydration Errors (MDX plugin to move callouts out of p-tags)

### ISSUE THREAD

**Issue by NicoZweifel** [mintlify/mint#258] opened 2023-01-26 22:02 UTC
**Describe the bug**
Hydration error caused by invalid html.

**To Reproduce**
New next.js app will fail to hydrate when using `<div>` or any block element inside `<p>` when using MDX and code blocks.
In the mint client you can reproduce it with any text paragraph that contains code blocks for example something like this:
![image](https://user-images.githubusercontent.com/34443492/214959285-97e84075-ea08-4959-9863-4ec3a90abcca.png)

**Expected behavior**
~~When using code blocks like that `<p>` elements should be replaced with `<span>` when they contain child components and not just text.~~

**Screenshots**
![image](https://user-images.githubusercontent.com/34443492/214958322-cf7a5bec-9910-4361-baaf-31f1613e1712.png)

**Device:**
 - OS: Windows 10
 - Browser chrome
 - Version 109.0.5414.119 (Official Build) (64-bit)

**Additional context**
The Pop-ins that are happening with code blocks are not related to this and happen most likely because of hook usage.
You can verify this by replacing the MDX Components individually that are used for `code` and `p`.

I will create a draft PR to demonstrate.

**Comment by NicoZweifel** [comment] 2023-01-27 01:52
The issue seems to be resolved after [this ](https://github.com/mintlify/components/pull/39).
No more extra `<pre>` elements are  generated after the CodeBlock is correctly rendered/hydrated, so no replacing is neccessary anymore.

**Comment by NicoZweifel** [comment] 2023-01-27 02:10
After some more testing, noticed that the `<Note>`  Component also causes this error because it seems to use `<div>`. The Changes from earlier in #259  with changing to span if the content has child components fixes it.
I am not sure how to fix it otherwise, if we want to use components in the markdown directly between text:
```mdx
<Accordion title="Customize the branding">
    Branding mostly happens in the `mint.json` file. You can learn more about all available [configuration properties](https://mintlify.com/docs/settings/global).

    #### Update the logo

    Update `logo` folder with the light and dark version of your logo (can be svg or png).
    <Note>Make sure that the path matches the values set in `logo` of `mint.json`</Note>

    #### Customize the colors

    Populate the `colors` object with colors that match your brand

    #### Update the favicon

    Change the `favicon.png` with an image of the favicon

    #### Update footer social icons

    Update `footerSocials` with the right `[platform]: [url]` key-value pair
  </Accordion>```

**Comment by tobias-mintlify** [comment] 2023-01-27 02:44
Two ideas:

1. Don't let MDX put the callout inside the paragraph. We never intended them to be nested inside p-tags and the margins are weird because of it.
2. Worst case, we can use the Typography component for callouts. Then callouts would automatically become spans when used inside a paragraph.

**Comment by NicoZweifel** [comment] 2023-01-27 03:04
The main issue is that everybody has to remember to make a newline before using a component when writing mdx:
For example this newline will fix it for the starter template `<Note>`
https://github.com/mintlify/starter/pull/2

Checking for `string` is kind of broken because it ignores valid inline elements but I feel like some sort of mechanism to catch this would be nice.

**Comment by NicoZweifel** [comment] 2023-01-27 03:09
There is some other things that can be done like checking children recursively but I really don't like where this is going :smiley:.
I guess manually inserting a newline when there is a component immediately after text could work.

**Comment by hahnbeelee** [comment] 2023-01-27 03:31
If you look in [client/src/utils/mdx](https://github.com/mintlify/mint/tree/main/client/src/utils/mdx) you can see we use remark/rehype plugins to alter the [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) of the MDX content. When using plugins you're interacting with the data structure post the parsing step, so it makes it really easy to understand, interact with, and edit the content. My favorite way of debugging the tree is to use the [next.js debugger](https://nextjs.org/docs/advanced-features/debugging) ([vscode instructions](https://github.com/mintlify/mint/blob/main/client/README.md#debugging-in-vs-code)). If a random <p> element is being inserted you can probably take it out by altering the tree.

**Comment by hahnbeelee** [comment] 2023-01-27 03:40
Some pseudocode would be:
If a child `Tip` exists inside a parent `p`, take `Tip` out and place it next to the `p`

**Comment by tobias-mintlify** [comment] 2023-01-27 03:41
We might be able to talk the tree to detect any callouts that are children of a p-tag and move them to be siblings instead. We do something similar when we get all code blocks and detect if they're in a code group.

**Comment by NicoZweifel** [comment] 2023-01-27 03:41
In this case MDX actually does what it is supposed to do, it is just that you're not supposed to put blocking elements inside a paragraph.
I think we could alter the tree in 2 ways:

- inserting a new line so the mdx gets parsed properly
- close paragraph and open a new paragraph after the component, otherwise the layout is broken.

But then again Users could actually be meaning to put a blocking component between text, which makes it a weird edge case.

**Comment by NicoZweifel** [comment] 2023-01-27 03:42
> Some pseudocode would be: If a child `Tip` exists inside a parent `p`, take `Tip` out and place it next to the `p`

That would change the layout tho if you mean to put it after the next closing `p` tag.

**Comment by tobias-mintlify** [comment] 2023-01-27 03:43
Some components like Tooltip are meant to go in the p-tag: `<p>Text <Tooltip>hover over me</Tooltip></p>`

We'd want to hardcode the callouts (Note, Tip) so only those are affected by the MDX plugin. We can't use regex because that would break in situations where you typed `<Note>` inside a code block. For example, all the callout code examples on Mintlify's docs would have extra blank lines added to them.

**Comment by hahnbeelee** [comment] 2023-01-27 03:43
> That would change the layout tho if you mean to put it after the next closing p tag.
We can add one more check that checks if it is the last child inside the `p`?

**Comment by tobias-mintlify** [comment] 2023-01-27 03:45
> > That would change the layout tho if you mean to put it after the next closing p tag.
> We can add one more check that checks if it is the last child inside the `p`?

We could also just split it.

p
 - Text
 - - Callout
 - - - Text

Could become

p
- text

Callout

p
- text

Basically keeping the order of everything in the same depth.

**Comment by NicoZweifel** [comment] 2023-01-27 03:46
Yea that's what I meant by closing and opening a new one.

**Comment by tobias-mintlify** [comment] 2023-01-27 03:47
Updated the title so we can keep track of this specific task. Let's make other issues if we find other types of hydration issues.

**Comment by NicoZweifel** [comment] 2023-01-27 14:14
After the recent fixes and improvements to the code blocks and some more work on the grouped ones, I made some new observations in https://github.com/mintlify/components/pull/43. 
It seems that now only the CodeBlocks for some languages and with custom elements inside will fail to hydrate i.e.:
  - does work: 
  ```bash
  yarn global add mintlify
  ```
- hydration error when using tsx:
 ```tsx
 console.log('hello world')
```
and then sth like 

```tsx
<Card title="Click on me" href="/components/card-group">
  This is how you use a card with an icon and a link. Clicking on this card
  brings you to the Card Group page.
</Card>
```
will not work either unfortunately. 

@tobias-mintlify You mentioned earlier this could be caused by the user preference colors if i remember right? Could that explain why `bash` renders with colors but `tsx` fails with a hydration error.

**Comment by tobias-mintlify** [comment] 2023-01-28 01:41
The `mint.json` only affects the tab colors. If that were the cause you would see hydration errors on every language not just tsx.

I encountered a different error trying to test the WIP though. Let's continue the conversation in https://github.com/mintlify/components/pull/43 to keep it all in one place.

**Comment by tobias-mintlify** [comment] 2023-02-07 20:53
@NicoZweifel can we close this?

**Comment by NicoZweifel** [comment] 2023-02-07 21:08
Yeah I think we can close it. The remaining hydration errors are because of something related to code highlighting or if the user does put mdx components right after text (without newline to close ’p’). We can track it in a different Issue.

**Closed** 2023-02-08 00:53 UTC
Labels: bug
